using System.Diagnostics;
using System.Globalization;
using System.Text;
using Lensee.Modules.Reporting.Application;
using Lensee.Modules.Reporting.Application.Abstractions;
using Lensee.Modules.Reporting.Application.Models;
using Lensee.Modules.Reporting.Configuration;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Lensee.Modules.Reporting.Infrastructure;

public sealed class DocumentRenderingException : Exception
{
    public DocumentRenderingException(string message, Exception innerException) : base(message, innerException) { }
}

public sealed class DocumentRenderCapacityException : Exception
{
    public DocumentRenderCapacityException() : base("Document rendering is at capacity. Retry shortly.") { }
}

public sealed class DocumentBrandingProvider(IOptions<ReportingOptions> options) : IDocumentBrandingProvider
{
    public DocumentBranding Branding { get; } = new(
        options.Value.Branding.CompanyNameArabic,
        options.Value.Branding.CompanyNameEnglish,
        options.Value.Branding.AddressArabic,
        options.Value.Branding.AddressEnglish,
        options.Value.Branding.Phone,
        options.Value.Branding.TaxNumber,
        options.Value.Branding.CommercialRegistration,
        options.Value.Branding.CurrencyCode,
        options.Value.Branding.ArabicFontFamily,
        options.Value.Branding.LatinFontFamily,
        DecodeLogo(options.Value.Branding.LogoBase64));

    private static byte[]? DecodeLogo(string? value) =>
        string.IsNullOrWhiteSpace(value) ? null : Convert.FromBase64String(value);
}

public sealed class DocumentLocalizer : IDocumentLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> Arabic = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["GeneratedAt"] = "تاريخ الإنشاء",
        ["GeneratedBy"] = "أنشأه",
        ["Reference"] = "المرجع",
        ["Page"] = "صفحة",
        ["Of"] = "من",
        ["NoData"] = "لا توجد بيانات للمعايير المحددة.",
        ["InternalDocument"] = "مستند أعمال داخلي",
        ["Summary"] = "الملخص"
    };

    public string Text(string key, DocumentLanguage language)
    {
        var english = key switch
        {
            "GeneratedAt" => "Generated at",
            "GeneratedBy" => "Generated by",
            "Reference" => "Reference",
            "Page" => "Page",
            "Of" => "of",
            "NoData" => "No data found for the selected criteria.",
            "InternalDocument" => "Internal business document",
            "Summary" => "Summary",
            _ => key
        };
        var arabic = Arabic.TryGetValue(key, out var translated) ? translated : key;
        return language switch
        {
            DocumentLanguage.Arabic => arabic,
            DocumentLanguage.Bilingual => $"{arabic} / {english}",
            _ => english
        };
    }
}

public sealed class DocumentFileNameGenerator : IFileNameGenerator
{
    private static readonly HashSet<char> InvalidCharacters = ['/', '\\', ':', '*', '?', '"', '<', '>', '|'];

    public string Generate(DocumentMetadata metadata, string extension)
    {
        var reference = string.IsNullOrWhiteSpace(metadata.ReferenceNumber) ? null : $"_{metadata.ReferenceNumber}";
        var raw = $"{ToPascalCase(metadata.DocumentKey)}{reference}_{metadata.GeneratedAtUtc:yyyy-MM-dd}.{extension.TrimStart('.')}";
        var safe = new string(raw.Select(character => InvalidCharacters.Contains(character) || char.IsControl(character) ? '_' : character).ToArray());
        return safe.Length <= 180 ? safe : safe[..180];
    }

    private static string ToPascalCase(string value) => string.Concat(value
        .Split(['-', '_', ' '], StringSplitOptions.RemoveEmptyEntries)
        .Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
}

public sealed class DocumentExportService(
    IEnumerable<IDocumentRenderer> renderers,
    IFileNameGenerator fileNameGenerator,
    ILogger<DocumentExportService> logger) : IDocumentExportService
{
    private readonly IReadOnlyDictionary<ExportFormat, IDocumentRenderer> _renderers = renderers.ToDictionary(renderer => renderer.Format);
    private readonly SemaphoreSlim _documentRenderGate = new(1, 1);
    private int _waitingDocumentRenders;

    public async Task<DocumentExportResult> ExportAsync(
        DocumentModel document,
        ExportFormat format,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (!_renderers.TryGetValue(format, out var renderer))
        {
            throw new NotSupportedException($"Export format '{format}' is not registered.");
        }

        var gateAcquired = false;
        if (format is ExportFormat.Pdf or ExportFormat.Excel)
        {
            gateAcquired = await _documentRenderGate.WaitAsync(0, cancellationToken);
            if (!gateAcquired)
            {
                if (Interlocked.Increment(ref _waitingDocumentRenders) > 2)
                {
                    Interlocked.Decrement(ref _waitingDocumentRenders);
                    throw new DocumentRenderCapacityException();
                }
                try
                {
                    await _documentRenderGate.WaitAsync(cancellationToken);
                    gateAcquired = true;
                }
                finally
                {
                    Interlocked.Decrement(ref _waitingDocumentRenders);
                }
            }
        }

        var stopwatch = Stopwatch.StartNew();
        try
        {
            var rendered = await renderer.RenderAsync(document, cancellationToken);
            var fileName = fileNameGenerator.Generate(document.Metadata, rendered.FileExtension);
            var correlationId = Activity.Current?.TraceId.ToString() ?? "none";
            logger.LogInformation(
                "ReportGenerated ReportKey={ReportKey} Format={Format} Template={Template} Rows={Rows} DurationMs={DurationMs} CorrelationId={CorrelationId} Outcome={Outcome}",
                document.Metadata.DocumentKey,
                format,
                document.Metadata.Template,
                document.Metadata.RowCount,
                stopwatch.ElapsedMilliseconds,
                correlationId,
                "Success");
            return new DocumentExportResult(rendered.Content, fileName, rendered.ContentType);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception exception)
        {
            logger.LogError(
                exception,
                "ReportGenerationFailed ReportKey={ReportKey} Format={Format} Template={Template} Rows={Rows} DurationMs={DurationMs} CorrelationId={CorrelationId} Outcome={Outcome}",
                document.Metadata.DocumentKey,
                format,
                document.Metadata.Template,
                document.Metadata.RowCount,
                stopwatch.ElapsedMilliseconds,
                Activity.Current?.TraceId.ToString() ?? "none",
                "Failure");
            throw new DocumentRenderingException("The report could not be generated.", exception);
        }
        finally
        {
            if (gateAcquired) _documentRenderGate.Release();
        }
    }
}

public static class ReportingServiceCollectionExtensions
{
    public static IServiceCollection AddReportingDocuments(this IServiceCollection services, IConfiguration configuration)
    {
        ReportingFontRegistry.RegisterBundledFonts();
        services.AddOptions<ReportingOptions>()
            .Bind(configuration.GetSection(ReportingOptions.SectionName))
            .ValidateDataAnnotations()
            .Validate(options => options.QuestPdfLicense is "Community" or "Professional" or "Enterprise", "Unsupported QuestPDF license type.")
            .Validate(options => IsValidBase64(options.Branding.LogoBase64), "Reporting branding logo must be valid base64.")
            .ValidateOnStart();

        var license = configuration[$"{ReportingOptions.SectionName}:QuestPdfLicense"] ?? "Community";
        QuestPDF.Settings.License = license switch
        {
            "Professional" => QuestPDF.Infrastructure.LicenseType.Professional,
            "Enterprise" => QuestPDF.Infrastructure.LicenseType.Enterprise,
            _ => QuestPDF.Infrastructure.LicenseType.Community
        };
        QuestPDF.Settings.UseEnvironmentFonts = false;

        services.AddSingleton<IReportCatalog, ReportCatalog>();
        services.AddSingleton<IDocumentLocalizer, DocumentLocalizer>();
        services.AddSingleton<IFileNameGenerator, DocumentFileNameGenerator>();
        services.AddSingleton<IDocumentBrandingProvider, DocumentBrandingProvider>();
        services.AddSingleton<IDocumentRenderer, QuestPdfDocumentRenderer>();
        services.AddSingleton<IDocumentRenderer, ClosedXmlDocumentRenderer>();
        services.AddSingleton<IDocumentRenderer, CsvDocumentRenderer>();
        services.AddSingleton<IDocumentExportService, DocumentExportService>();
        return services;
    }

    private static bool IsValidBase64(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return true;
        Span<byte> buffer = new byte[value.Length];
        return Convert.TryFromBase64String(value, buffer, out _);
    }

    public static bool TryParseLanguage(string? value, out DocumentLanguage language)
    {
        language = value?.Trim().ToLowerInvariant() switch
        {
            "ar" or "arabic" => DocumentLanguage.Arabic,
            "bi" or "bilingual" => DocumentLanguage.Bilingual,
            _ => DocumentLanguage.English
        };
        return string.IsNullOrWhiteSpace(value) || value.Trim().ToLowerInvariant() is "ar" or "arabic" or "en" or "english" or "bi" or "bilingual";
    }

    public static bool TryParseFormat(string? value, out ExportFormat format)
    {
        format = value?.Trim().ToLowerInvariant() switch
        {
            "xlsx" or "excel" => ExportFormat.Excel,
            "csv" => ExportFormat.Csv,
            _ => ExportFormat.Pdf
        };
        return string.IsNullOrWhiteSpace(value) || value.Trim().ToLowerInvariant() is "pdf" or "xlsx" or "excel" or "csv";
    }

    internal static string CellText(DocumentCell cell, string? numberFormat = null) => cell switch
    {
        DocumentCell.Text text => text.Value,
        DocumentCell.Code code => code.Value,
        DocumentCell.Integer integer => integer.Value.ToString(CultureInfo.InvariantCulture),
        DocumentCell.Number number => number.Value.ToString(numberFormat ?? "0.####", CultureInfo.InvariantCulture),
        DocumentCell.Decimal decimalValue => decimalValue.Value.ToString(numberFormat ?? "0.####", CultureInfo.InvariantCulture),
        DocumentCell.Money money => money.Value.ToString(numberFormat ?? "0.00", CultureInfo.InvariantCulture),
        DocumentCell.Percentage percentage => percentage.Value.ToString(numberFormat ?? "0.00%", CultureInfo.InvariantCulture),
        DocumentCell.Date date => date.Value.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
        DocumentCell.DateTimeValue dateTime => dateTime.Value.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture),
        DocumentCell.Boolean boolean => boolean.Value ? "Yes" : "No",
        _ => string.Empty
    };
}
