// <auto-generated />
using System;
using Lensee.Modules.Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Finance.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260920095437_AddExpensesAndCLevelWithdrawals")]
    partial class AddExpensesAndCLevelWithdrawals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("AssignedToCLevelUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_c_level_user_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("PostedFinanceLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_finance_ledger_entry_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReplacedByWithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_withdrawal_id");

                    b.Property<Guid?>("ReversesWithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_withdrawal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("PostedFinanceLedgerEntryId")
                        .IsUnique()
                        .HasFilter("(posted_finance_ledger_entry_id is not null)");

                    b.HasIndex("ReplacedByWithdrawalId")
                        .IsUnique()
                        .HasFilter("(replaced_by_withdrawal_id is not null)");

                    b.HasIndex("AssignedToCLevelUserId", "Status");

                    b.ToTable("c_level_withdrawals", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_c_level_withdrawal_amount", "amount > 0");

                            t.HasCheckConstraint("chk_c_level_withdrawal_reason", "length(trim(reason)) > 0");

                            t.HasCheckConstraint("chk_c_level_withdrawal_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("finance_accounts", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_account_type", "type in ('CashOnHand','BankAccount','Wallet')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("PostedFinanceLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_finance_ledger_entry_id");

                    b.Property<Guid?>("ReplacedByExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_expense_id");

                    b.Property<Guid?>("ReversesExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_expense_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("PostedFinanceLedgerEntryId")
                        .IsUnique()
                        .HasFilter("(posted_finance_ledger_entry_id is not null)");

                    b.HasIndex("ReplacedByExpenseId")
                        .IsUnique()
                        .HasFilter("(replaced_by_expense_id is not null)");

                    b.ToTable("finance_expenses", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_expense_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_expense_category", "category in ('Salary','Rent','SocialMedia','SoftwareAndTechnologySubscriptions','Other')");

                            t.HasCheckConstraint("chk_finance_expense_other_description", "category <> 'Other' or length(trim(coalesce(description, ''))) > 0");

                            t.HasCheckConstraint("chk_finance_expense_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Posted")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasFilter("(external_reference is not null)");

                    b.HasIndex("FinanceAccountId", "BusinessDate");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("finance_ledger_entries", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_ledger_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_ledger_direction", "direction in ('Debit','Credit')");

                            t.HasCheckConstraint("chk_finance_ledger_status", "status in ('Posted','Reversed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceOpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Credit")
                        .HasColumnName("direction");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<Guid?>("PostedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_entry_id");

                    b.Property<Guid?>("ReplacedByOpeningBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_opening_balance_id");

                    b.Property<Guid?>("ReversesOpeningBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_opening_balance_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("PostedEntryId")
                        .IsUnique()
                        .HasFilter("(posted_entry_id is not null)");

                    b.ToTable("finance_opening_balances", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_opening_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_opening_direction", "direction in ('Debit','Credit')");

                            t.HasCheckConstraint("chk_finance_opening_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.PaymentMovementRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<string>("NormalizedExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_external_reference");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Posted")
                        .HasColumnName("status");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("track");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedExternalReference")
                        .IsUnique()
                        .HasFilter("(normalized_external_reference is not null)");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("payment_movement_registry", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_payment_movement_amount", "amount > 0");

                            t.HasCheckConstraint("chk_payment_movement_status", "status in ('Posted','Reversed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawal", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceExpense", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceLedgerEntry", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany("Entries")
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceOpeningBalance", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceAccount", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
