// <auto-generated />
using System;
using Lensee.Modules.Finance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Finance.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260923221316_EnforceOneFinanceOpeningRoot")]
    partial class EnforceOneFinanceOpeningRoot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("AssignedToCLevelUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_c_level_user_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CorrectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("correction_note");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("PostedFinanceLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_finance_ledger_entry_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReplacedByWithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_withdrawal_id");

                    b.Property<Guid?>("ReversesWithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_withdrawal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("PostedFinanceLedgerEntryId")
                        .IsUnique()
                        .HasFilter("(posted_finance_ledger_entry_id is not null)");

                    b.HasIndex("ReplacedByWithdrawalId")
                        .IsUnique()
                        .HasFilter("(replaced_by_withdrawal_id is not null)");

                    b.HasIndex("AssignedToCLevelUserId", "Status");

                    b.ToTable("c_level_withdrawals", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_c_level_withdrawal_amount", "amount > 0");

                            t.HasCheckConstraint("chk_c_level_withdrawal_reason", "length(trim(reason)) > 0");

                            t.HasCheckConstraint("chk_c_level_withdrawal_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawalRepayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PostedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_entry_id");

                    b.Property<Guid>("WithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawal_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasFilter("(external_reference is not null)");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("WithdrawalId");

                    b.ToTable("c_level_withdrawal_repayments", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_withdrawal_repayment_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("finance_accounts", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_account_type", "type in ('CashOnHand','BankAccount','Wallet')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Kind", "Code")
                        .IsUnique();

                    b.HasIndex("Kind", "SortOrder");

                    b.ToTable("finance_categories", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_category_kind", "kind in ('Expense','Withdrawal')");

                            t.HasCheckConstraint("chk_finance_category_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("CorrectionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("correction_note");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("PostedFinanceLedgerEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_finance_ledger_entry_id");

                    b.Property<Guid?>("ReplacedByExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_expense_id");

                    b.Property<Guid?>("ReversesExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_expense_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FinanceAccountId");

                    b.HasIndex("PostedFinanceLedgerEntryId")
                        .IsUnique()
                        .HasFilter("(posted_finance_ledger_entry_id is not null)");

                    b.HasIndex("ReplacedByExpenseId")
                        .IsUnique()
                        .HasFilter("(replaced_by_expense_id is not null)");

                    b.ToTable("finance_expenses", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_expense_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_expense_other_description", "category <> 'Other' or length(trim(coalesce(description, ''))) > 0");

                            t.HasCheckConstraint("chk_finance_expense_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected','Pending','Paid')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Posted")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasFilter("(external_reference is not null)");

                    b.HasIndex("FinanceAccountId", "BusinessDate");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("finance_ledger_entries", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_ledger_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_ledger_direction", "direction in ('Debit','Credit')");

                            t.HasCheckConstraint("chk_finance_ledger_status", "status in ('Posted','Reversed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceOpeningBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Credit")
                        .HasColumnName("direction");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<Guid?>("PostedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_entry_id");

                    b.Property<Guid?>("ReplacedByOpeningBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_opening_balance_id");

                    b.Property<Guid?>("ReversesOpeningBalanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_opening_balance_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("FinanceAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_finance_opening_one_root_per_account")
                        .HasFilter("(reverses_opening_balance_id is null and status <> 'Rejected')");

                    b.HasIndex("PostedEntryId")
                        .IsUnique()
                        .HasFilter("(posted_entry_id is not null)");

                    b.ToTable("finance_opening_balances", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_opening_amount", "amount > 0");

                            t.HasCheckConstraint("chk_finance_opening_direction", "direction in ('Debit','Credit')");

                            t.HasCheckConstraint("chk_finance_opening_status", "status in ('Draft','PendingReview','Posted','Rejected','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date")
                        .HasColumnName("business_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DestinationAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_account_id");

                    b.Property<Guid>("DestinationEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_entry_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fee_amount");

                    b.Property<Guid?>("FeeExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_expense_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("SourceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_account_id");

                    b.Property<Guid>("SourceEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entry_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("ExternalReference")
                        .IsUnique()
                        .HasFilter("(external_reference is not null)");

                    b.HasIndex("SourceAccountId");

                    b.ToTable("finance_transfers", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_finance_transfer_accounts", "source_account_id <> destination_account_id");

                            t.HasCheckConstraint("chk_finance_transfer_amount", "amount > 0 and fee_amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.PaymentMovementRegistry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("MovementMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("movement_method");

                    b.Property<string>("NormalizedExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_external_reference");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Posted")
                        .HasColumnName("status");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("track");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedExternalReference")
                        .IsUnique()
                        .HasFilter("(normalized_external_reference is not null)");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.ToTable("payment_movement_registry", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_payment_movement_amount", "amount > 0");

                            t.HasCheckConstraint("chk_payment_movement_status", "status in ('Posted','Reversed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.ReconciliationImportPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("applied_at");

                    b.Property<Guid?>("AppliedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applied_by_user_id");

                    b.Property<string>("ApplyIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("apply_idempotency_key");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("exported_at_utc");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_sha256");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by_user_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("signature");

                    b.Property<string>("Signer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("signer");

                    b.Property<DateOnly>("SourcePeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("source_period_end");

                    b.Property<DateOnly>("SourcePeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("source_period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Registered")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApplyIdempotencyKey")
                        .IsUnique()
                        .HasFilter("(apply_idempotency_key is not null)");

                    b.HasIndex("PayloadSha256")
                        .IsUnique();

                    b.ToTable("reconciliation_import_packages", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_reconciliation_package_period", "source_period_start <= source_period_end");

                            t.HasCheckConstraint("chk_reconciliation_package_status", "status in ('Registered','Previewed','Applied','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.ReconciliationImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalTrack")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canonical_track");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PendingReview")
                        .HasColumnName("decision");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("decision_reason");

                    b.Property<string>("OriginalPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("original_payload");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid")
                        .HasColumnName("package_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<string>("RowType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("row_type");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_reference");

                    b.HasKey("Id");

                    b.HasIndex("PackageId", "Decision");

                    b.HasIndex("PackageId", "RowNumber")
                        .IsUnique();

                    b.HasIndex("PackageId", "SourceReference")
                        .IsUnique();

                    b.ToTable("reconciliation_import_rows", "finance", t =>
                        {
                            t.HasCheckConstraint("chk_reconciliation_row_decision", "decision in ('Approved','PendingReview','Rejected','Applied')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawal", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.CLevelWithdrawalRepayment", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lensee.Modules.Finance.Data.CLevelWithdrawal", null)
                        .WithMany()
                        .HasForeignKey("WithdrawalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceCategory", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceExpense", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceLedgerEntry", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany("Entries")
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceOpeningBalance", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", "FinanceAccount")
                        .WithMany()
                        .HasForeignKey("FinanceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FinanceAccount");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceTransfer", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lensee.Modules.Finance.Data.FinanceAccount", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.ReconciliationImportRow", b =>
                {
                    b.HasOne("Lensee.Modules.Finance.Data.ReconciliationImportPackage", "Package")
                        .WithMany("Rows")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.FinanceAccount", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Lensee.Modules.Finance.Data.ReconciliationImportPackage", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
