// <auto-generated />
using System;
using Lensee.Modules.Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260705054629_FixCatalogSellModeConstraint")]
    partial class FixCatalogSellModeConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("brands_pkey");

                    b.ToTable("brands", "catalog");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("categories_pkey");

                    b.HasIndex(new[] { "ParentId" }, "idx_categories_parent");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ClinicalParams")
                        .HasColumnType("jsonb")
                        .HasColumnName("clinical_params");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ExpiryType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("expiry_type");

                    b.Property<string>("ExtendedAttributes")
                        .HasColumnType("jsonb")
                        .HasColumnName("extended_attributes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OpenedExpiryDuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opened_expiry_duration");

                    b.Property<int?>("PiecesPerPack")
                        .HasColumnType("integer")
                        .HasColumnName("pieces_per_pack");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("product_type");

                    b.Property<string>("SealedExpiryDuration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sealed_expiry_duration");

                    b.Property<string>("OpenedExpiryRate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("opened_expiry_rate");

                    b.Property<string>("SellMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sell_mode");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex(new[] { "IsActive" }, "idx_products_active");

                    b.HasIndex(new[] { "BrandId" }, "idx_products_brand");

                    b.HasIndex(new[] { "CategoryId" }, "idx_products_category");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("chk_products_pieces_per_pack", "pieces_per_pack is null or pieces_per_pack > 0");

                            t.HasCheckConstraint("chk_products_product_type", "product_type in ('Lens','Solution')");

                            t.HasCheckConstraint("chk_products_opened_expiry_rate", "opened_expiry_rate is null or opened_expiry_rate in ('Daily','Monthly','Annual')");

                            t.HasCheckConstraint("chk_products_sell_mode", "sell_mode in ('SealedPackOnly','SinglePiece','Both')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Barcode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("barcode");

                    b.Property<string>("ColorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_name");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PowerSign")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("power_sign");

                    b.Property<decimal?>("PowerValue")
                        .HasColumnType("numeric")
                        .HasColumnName("power_value");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code");

                    b.HasKey("Id")
                        .HasName("skus_pkey");

                    b.HasIndex(new[] { "ProductId" }, "idx_skus_product");

                    b.HasIndex(new[] { "SkuCode" }, "idx_skus_sku_code");

                    b.HasIndex(new[] { "SkuCode" }, "skus_sku_code_key")
                        .IsUnique();

                    b.ToTable("skus", "catalog", t =>
                        {
                            t.HasCheckConstraint("chk_skus_power_sign", "power_sign is null or power_sign in ('+','-')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Category", b =>
                {
                    b.HasOne("Lensee.Modules.Catalog.Data.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("categories_parent_id_fkey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Product", b =>
                {
                    b.HasOne("Lensee.Modules.Catalog.Data.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("products_brand_id_fkey");

                    b.HasOne("Lensee.Modules.Catalog.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("products_category_id_fkey");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Sku", b =>
                {
                    b.HasOne("Lensee.Modules.Catalog.Data.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("skus_product_id_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Lensee.Modules.Catalog.Data.Product", b =>
                {
                    b.Navigation("Skus");
                });
#pragma warning restore 612, 618
        }
    }
}
