// <auto-generated />
using System;
using Lensee.Modules.Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.InventoryBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreatedFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("inventory_batches_pkey");

                    b.HasIndex(new[] { "ExpiryDate" }, "idx_inv_batches_expiry")
                        .HasFilter("(expiry_date IS NOT NULL)");

                    b.HasIndex(new[] { "LocationId", "SkuId" }, "idx_inv_batches_location_sku");

                    b.ToTable("inventory_batches", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_inventory_batches_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.InventoryReceiptCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<int?>("ResponseBatchQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("response_batch_quantity");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StockTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_transaction_id");

                    b.HasKey("Id")
                        .HasName("inventory_receipt_commands_pkey");

                    b.HasIndex("BatchId");

                    b.HasIndex(new[] { "Key" }, "uq_inventory_receipt_commands_key")
                        .IsUnique();

                    b.HasIndex(new[] { "StockTransactionId" }, "uq_inventory_receipt_commands_stock_transaction")
                        .IsUnique()
                        .HasFilter("(stock_transaction_id IS NOT NULL)");

                    b.ToTable("inventory_receipt_commands", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_inventory_receipt_command_status", "status in ('Pending','Completed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("locations_pkey");

                    b.ToTable("locations", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_locations_type", "location_type in ('MainWarehouse','SubWarehouse','Online')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.OpenedPieceLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateOnly?>("BatchExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("batch_expiry_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CreatedFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("created_from");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("LoosePieceQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("loose_piece_quantity");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<DateOnly>("OpenedDate")
                        .HasColumnType("date")
                        .HasColumnName("opened_date");

                    b.Property<DateOnly?>("PieceExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("piece_expiry_date");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<Guid>("SourceBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_batch_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("opened_piece_lots_pkey");

                    b.HasIndex(new[] { "LocationId", "SkuId", "PieceExpiryDate" }, "idx_opened_piece_lots_fefo");

                    b.ToTable("opened_piece_lots", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_opened_piece_lots_quantity", "loose_piece_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.StockBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("AvailableQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("available_qty");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("ReservedInWarehouseQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_in_warehouse_qty");

                    b.Property<int>("ReservedWithRepQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_with_rep_qty");

                    b.Property<int>("RowVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_version");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int?>("TargetQty")
                        .HasColumnType("integer")
                        .HasColumnName("target_qty");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("stock_balances_pkey");

                    b.HasIndex(new[] { "LocationId", "AvailableQty" }, "idx_stock_balances_available");

                    b.HasIndex(new[] { "SkuId" }, "idx_stock_balances_sku");

                    b.HasIndex(new[] { "LocationId", "SkuId" }, "uq_location_sku")
                        .IsUnique();

                    b.ToTable("stock_balances", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_stock_balances_available", "available_qty >= 0");

                            t.HasCheckConstraint("chk_stock_balances_reserved_rep", "reserved_with_rep_qty >= 0");

                            t.HasCheckConstraint("chk_stock_balances_reserved_warehouse", "reserved_in_warehouse_qty >= 0");

                            t.HasCheckConstraint("chk_stock_balances_row_version", "row_version >= 0");

                            t.HasCheckConstraint("chk_stock_balances_target", "target_qty is null or target_qty >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_change");

                    b.Property<Guid?>("ReferenceOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_operation_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("stock_transactions_pkey");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "ReferenceOperationId" }, "idx_stock_txn_operation")
                        .HasFilter("(reference_operation_id IS NOT NULL)");

                    b.HasIndex(new[] { "SkuId", "LocationId", "CreatedAt" }, "idx_stock_txn_sku_location")
                        .IsDescending(false, false, true);

                    b.HasIndex(new[] { "UserId" }, "idx_stock_txn_user");

                    b.ToTable("stock_transactions", "inventory", t =>
                        {
                            t.HasCheckConstraint("chk_txn_type", "transaction_type in ('Receipt','Sale','ReserveInWarehouse','ReserveWithRep','ReserveReleaseInWarehouse','ReserveReleaseWithRep','WriteOff','SupplyOut','SupplyIn','StocktakeAdjustment','ChangeOut','ChangeIn','ReturnIn')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.InventoryBatch", b =>
                {
                    b.HasOne("Lensee.Modules.Inventory.Data.Location", "Location")
                        .WithMany("InventoryBatches")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("inventory_batches_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.InventoryReceiptCommand", b =>
                {
                    b.HasOne("Lensee.Modules.Inventory.Data.InventoryBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Lensee.Modules.Inventory.Data.StockTransaction", null)
                        .WithMany()
                        .HasForeignKey("StockTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.OpenedPieceLot", b =>
                {
                    b.HasOne("Lensee.Modules.Inventory.Data.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("opened_piece_lots_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.StockBalance", b =>
                {
                    b.HasOne("Lensee.Modules.Inventory.Data.Location", "Location")
                        .WithMany("StockBalances")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("stock_balances_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.StockTransaction", b =>
                {
                    b.HasOne("Lensee.Modules.Inventory.Data.Location", "Location")
                        .WithMany("StockTransactions")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("stock_transactions_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Lensee.Modules.Inventory.Data.Location", b =>
                {
                    b.Navigation("InventoryBatches");

                    b.Navigation("StockBalances");

                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
