// <auto-generated />
using System;
using System.Collections.Generic;
using Lensee.Modules.CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.CRM.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260726225310_AddShopifyExternalCustomerKey")]
    partial class AddShopifyExternalCustomerKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.CRM.Data.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("business_name");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("business_type");

                    b.Property<string>("ContactPersonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_person_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_customer_id");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("external_provider");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<List<string>>("PhoneNumbers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("phone_numbers")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("merchants_pkey");

                    b.HasIndex(new[] { "Status" }, "idx_merchants_status")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex(new[] { "ExternalProvider", "ExternalCustomerId" }, "uq_merchants_external_customer")
                        .IsUnique()
                        .HasFilter("(external_provider IS NOT NULL AND external_customer_id IS NOT NULL)");

                    b.ToTable("merchants", "crm", t =>
                        {
                            t.HasCheckConstraint("chk_merchants_status", "status in ('Active','Inactive')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.CRM.Data.MerchantNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("merchant_notes_pkey");

                    b.HasIndex(new[] { "MerchantId" }, "idx_merchant_notes_merchant");

                    b.ToTable("merchant_notes", "crm");
                });

            modelBuilder.Entity("Lensee.Modules.CRM.Data.Representative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AssignedLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_location_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<List<string>>("PhoneNumbers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("phone_numbers")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'External'::character varying");

                    b.HasKey("Id")
                        .HasName("representatives_pkey");

                    b.HasIndex(new[] { "Status" }, "idx_representatives_status")
                        .HasFilter("(is_deleted = false)");

                    b.ToTable("representatives", "crm", t =>
                        {
                            t.HasCheckConstraint("chk_representatives_status", "status in ('Active','Inactive')");

                            t.HasCheckConstraint("chk_representatives_type", "type in ('Internal','External')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.CRM.Data.MerchantNote", b =>
                {
                    b.HasOne("Lensee.Modules.CRM.Data.Merchant", "Merchant")
                        .WithMany("MerchantNotes")
                        .HasForeignKey("MerchantId")
                        .IsRequired()
                        .HasConstraintName("merchant_notes_merchant_id_fkey");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Lensee.Modules.CRM.Data.Merchant", b =>
                {
                    b.Navigation("MerchantNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
