// <auto-generated />
using System;
using Lensee.Modules.Payments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Payments.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20260923220130_EnforceOneMerchantOpeningRoot")]
    partial class EnforceOneMerchantOpeningRoot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Payments.Data.CashRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<Guid?>("FinancialAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_adjustment_id");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type")
                        .HasDefaultValueSql("'CashReceived'::character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Completed'::character varying");

                    b.Property<string>("SubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_type");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id")
                        .HasName("cash_records_pkey");

                    b.HasIndex(new[] { "FinancialAdjustmentId" }, "idx_cash_records_adjustment")
                        .HasFilter("(financial_adjustment_id IS NOT NULL)");

                    b.HasIndex(new[] { "PaymentDate" }, "idx_cash_records_date")
                        .IsDescending();

                    b.HasIndex(new[] { "MerchantId" }, "idx_cash_records_merchant")
                        .HasFilter("(merchant_id IS NOT NULL)");

                    b.HasIndex(new[] { "OperationId" }, "idx_cash_records_operation");

                    b.ToTable("cash_records", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_cash_amount", "amount > 0");

                            t.HasCheckConstraint("chk_cash_payment_type", "payment_type in ('CashReceived','CashRefund')");

                            t.HasCheckConstraint("chk_cash_record_scope", "operation_id is not null or merchant_id is not null");

                            t.HasCheckConstraint("chk_cash_status", "status in ('PendingAccountant','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.FinancialAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adjustment_type");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("LineageKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lineage_kind")
                        .HasDefaultValueSql("'SourceLinked'::character varying");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("PaymentLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_log_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReversesAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_adjustment_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PendingApproval'::character varying");

                    b.HasKey("Id")
                        .HasName("financial_adjustments_pkey");

                    b.HasIndex(new[] { "MerchantId" }, "idx_financial_adjustments_merchant");

                    b.HasIndex(new[] { "OperationId" }, "idx_financial_adjustments_operation")
                        .HasFilter("(operation_id IS NOT NULL)");

                    b.ToTable("financial_adjustments", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_financial_adjustment_amount", "amount > 0");

                            t.HasCheckConstraint("chk_financial_adjustment_status", "status in ('PendingApproval','Approved','Rejected','Completed','Cancelled','LegacyUnlinked')");

                            t.HasCheckConstraint("chk_financial_adjustment_type", "adjustment_type in ('AdditionalCharge','BalanceReduction','CashRefund')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.InstallmentSubLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateOnly>("DateReceived")
                        .HasColumnType("date")
                        .HasColumnName("date_received");

                    b.Property<DateTime>("DraftedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("drafted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DraftedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by");

                    b.Property<Guid?>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<Guid>("MainLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_log_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SubLogStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_log_status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id")
                        .HasName("installment_sub_logs_pkey");

                    b.HasIndex(new[] { "MainLogId" }, "idx_sub_logs_main_log");

                    b.HasIndex(new[] { "SubLogStatus" }, "idx_sub_logs_status");

                    b.ToTable("installment_sub_logs", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_sub_log_amount", "amount >= 0");

                            t.HasCheckConstraint("chk_sub_log_payment_method", "payment_method is null or payment_method in ('CashTransaction','CashHandToHand','BankTransfer','Wallet','Installment')");

                            t.HasCheckConstraint("chk_sub_log_status", "sub_log_status in ('Draft','PendingAdminReview','Confirmed','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MainPaymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("InitializedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("initialized_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("InitializedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initialized_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<decimal>("PendingAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pending_amount");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("OtherPayments")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PendingAdmin'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("main_payment_logs_pkey");

                    b.HasIndex(new[] { "AssignedTo" }, "idx_main_payment_assigned")
                        .HasFilter("(assigned_to IS NOT NULL)");

                    b.HasIndex(new[] { "MerchantId" }, "idx_main_payment_merchant");

                    b.HasIndex(new[] { "OperationId" }, "idx_main_payment_operation");

                    b.HasIndex(new[] { "Status" }, "idx_main_payment_status")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex(new[] { "OperationId" }, "uq_main_payment_operation_active")
                        .IsUnique()
                        .HasFilter("(is_deleted = false)");

                    b.ToTable("main_payment_logs", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_main_payment_amount_paid", "amount_paid >= 0");

                            t.HasCheckConstraint("chk_main_payment_method", "payment_method is null or payment_method in ('CashHandToHand','CashTransaction','BankTransfer','Wallet')");

                            t.HasCheckConstraint("chk_main_payment_paid_lte_total", "amount_paid + pending_amount <= total_amount");

                            t.HasCheckConstraint("chk_main_payment_pending_amount", "pending_amount >= 0");

                            t.HasCheckConstraint("chk_main_payment_scope", "scope in ('MerchantAccount','OtherPayments')");

                            t.HasCheckConstraint("chk_main_payment_status", "status in ('PendingAdmin','PendingAccountant','PendingAdminReview','Completed','Rejected','Cancelled')");

                            t.HasCheckConstraint("chk_main_payment_total_amount", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountClassificationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int>("CalendarYear")
                        .HasColumnType("integer")
                        .HasColumnName("calendar_year");

                    b.Property<string>("FlagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags_json");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsPartialYear")
                        .HasColumnType("boolean")
                        .HasColumnName("is_partial_year");

                    b.Property<decimal>("Score")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("score");

                    b.Property<string>("SettingsVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("settings_version");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "CalendarYear")
                        .IsUnique();

                    b.ToTable("merchant_account_classification_snapshots", "payments");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountCollectionDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AllocationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("allocations_json");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("DraftedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("drafted_at");

                    b.Property<Guid>("DraftedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by");

                    b.Property<Guid?>("FinanceAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("finance_account_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("MerchantAccount")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SourceOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_operation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasFilter("(assigned_to IS NOT NULL)");

                    b.HasIndex("AccountId", "Status", "DraftedAt");

                    b.ToTable("merchant_account_collection_drafts", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_collection_draft_amount", "amount > 0");

                            t.HasCheckConstraint("chk_merchant_collection_draft_method", "payment_method in ('CashHandToHand','CashTransaction','BankTransfer','Wallet')");

                            t.HasCheckConstraint("chk_merchant_collection_draft_scope", "scope = 'MerchantAccount'");

                            t.HasCheckConstraint("chk_merchant_collection_draft_status", "status in ('Draft','PendingAdminReview','Confirmed','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("credit_amount");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("debit_amount");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_type");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_entry_id");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("AccountId", "Sequence")
                        .IsUnique();

                    b.HasIndex("SourceType", "SourceId", "EntryType")
                        .IsUnique();

                    b.ToTable("merchant_account_entries", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_account_entry_amount", "(debit_amount > 0 and credit_amount = 0) or (credit_amount > 0 and debit_amount = 0)");

                            t.HasCheckConstraint("chk_merchant_account_entry_method", "payment_method is null or payment_method in ('CashHandToHand','CashTransaction','BankTransfer','Wallet')");

                            t.HasCheckConstraint("chk_merchant_account_entry_status", "status in ('Posted','Reversed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAllocationReconciliation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrectionChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("correction_charge_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ReplacementAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("replacement_allocation_id");

                    b.Property<Guid>("SourceAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_allocation_id");

                    b.HasKey("Id");

                    b.HasIndex("ReplacementAllocationId")
                        .IsUnique();

                    b.HasIndex("SourceAllocationId")
                        .IsUnique();

                    b.HasIndex("CorrectionChargeId", "CorrelationId")
                        .IsUnique();

                    b.ToTable("merchant_allocation_reconciliations", "payments");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantEntryAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("allocated_at");

                    b.Property<Guid>("AllocatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("allocated_by");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("ObligationId")
                        .HasColumnType("uuid")
                        .HasColumnName("obligation_id");

                    b.HasKey("Id");

                    b.HasIndex("ObligationId");

                    b.HasIndex("EntryId", "ObligationId")
                        .IsUnique();

                    b.ToTable("merchant_entry_allocations", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_entry_allocation_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantFinancialClosureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("SettlementAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProposalId", "OperationId")
                        .IsUnique();

                    b.ToTable("merchant_financial_closure_items", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_financial_closure_item_amount", "settlement_amount >= 0 and remaining_amount >= 0");

                            t.HasCheckConstraint("chk_financial_closure_item_decision", "decision in ('Pending','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantFinancialClosureProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasDefaultValue("PendingAdminReview");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("SubmittedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("(idempotency_key IS NOT NULL)");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("merchant_financial_closure_proposals", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_financial_closure_proposal_status", "status in ('PendingAdminReview','PartiallyApproved','Approved','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantOpeningBalanceCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<Guid?>("PostedEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_entry_id");

                    b.Property<Guid?>("ReplacedByChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_charge_id");

                    b.Property<Guid?>("ReversesChargeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_charge_id");

                    b.Property<string>("ReviewReason")
                        .HasColumnType("text")
                        .HasColumnName("review_reason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId")
                        .IsUnique()
                        .HasDatabaseName("ux_merchant_opening_one_root")
                        .HasFilter("(reverses_charge_id IS NULL AND status <> 'Rejected')");

                    b.HasIndex("PostedEntryId")
                        .IsUnique()
                        .HasFilter("(posted_entry_id IS NOT NULL)");

                    b.HasIndex("MerchantId", "Status");

                    b.ToTable("merchant_opening_balance_charges", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_opening_balance_amount", "amount > 0");

                            t.HasCheckConstraint("chk_opening_balance_status", "status in ('Draft','PendingReview','Posted','Rejected','Reversed','Corrected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantOperationObligation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("original_amount");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("posted_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasFilter("(operation_id IS NOT NULL)");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Status", "PostedAt");

                    b.ToTable("merchant_operation_obligations", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_obligation_amount", "original_amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantReceivableAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<long>("NextSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("next_sequence");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("OpenedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("opened_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId")
                        .IsUnique();

                    b.ToTable("merchant_receivable_accounts", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_account_next_sequence", "next_sequence > 0");

                            t.HasCheckConstraint("chk_merchant_account_status", "status in ('Open','Frozen','Closed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantRefundReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("paid_amount");

                    b.Property<Guid?>("PayoutEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_entry_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status");

                    b.ToTable("merchant_refund_reservations", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_merchant_refund_reservation_amount", "amount > 0");

                            t.HasCheckConstraint("chk_merchant_refund_reservation_paid_amount", "paid_amount >= 0 and paid_amount <= amount");

                            t.HasCheckConstraint("chk_merchant_refund_reservation_status", "status in ('PendingApproval','Approved','PartiallyPaid','Paid','Rejected','Cancelled')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.PaymentAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CollectionDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_draft_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_json");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("PaymentLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_log_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsDescending();

                    b.HasIndex("CollectionDraftId", "OccurredAt");

                    b.HasIndex("MerchantId", "OccurredAt");

                    b.HasIndex("PaymentLogId", "OccurredAt");

                    b.ToTable("payment_audit_events", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_payment_audit_amount", "amount is null or amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.PaymentIdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("payment_idempotency_keys_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_payment_idempotency_expires_at");

                    b.HasIndex(new[] { "Key", "Scope" }, "uq_payment_idempotency_key_scope")
                        .IsUnique();

                    b.ToTable("payment_idempotency_keys", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_payment_idempotency_status", "status in ('Pending','Completed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.InstallmentSubLog", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MainPaymentLog", "MainLog")
                        .WithMany("InstallmentSubLogs")
                        .HasForeignKey("MainLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("installment_sub_logs_main_log_id_fkey");

                    b.Navigation("MainLog");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountCollectionDraft", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantReceivableAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountEntry", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantReceivableAccount", "Account")
                        .WithMany("Entries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAllocationReconciliation", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantOpeningBalanceCharge", "CorrectionCharge")
                        .WithMany()
                        .HasForeignKey("CorrectionChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lensee.Modules.Payments.Data.MerchantEntryAllocation", "ReplacementAllocation")
                        .WithMany()
                        .HasForeignKey("ReplacementAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lensee.Modules.Payments.Data.MerchantEntryAllocation", "SourceAllocation")
                        .WithMany()
                        .HasForeignKey("SourceAllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_merchant_allocation_reconciliations_merchant_entry_allocat~1");

                    b.Navigation("CorrectionCharge");

                    b.Navigation("ReplacementAllocation");

                    b.Navigation("SourceAllocation");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantEntryAllocation", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantAccountEntry", "Entry")
                        .WithMany("Allocations")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lensee.Modules.Payments.Data.MerchantOperationObligation", "Obligation")
                        .WithMany("Allocations")
                        .HasForeignKey("ObligationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Obligation");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantFinancialClosureItem", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantFinancialClosureProposal", "Proposal")
                        .WithMany("Items")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantOperationObligation", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MerchantReceivableAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MainPaymentLog", b =>
                {
                    b.Navigation("InstallmentSubLogs");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantAccountEntry", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantFinancialClosureProposal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantOperationObligation", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MerchantReceivableAccount", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
