// <auto-generated />
using System;
using Lensee.Modules.Payments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Payments.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Payments.Data.CashRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("FinancialAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("financial_adjustment_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_type")
                        .HasDefaultValueSql("'CashReceived'::character varying");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Completed'::character varying");

                    b.Property<string>("SubType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_type");

                    b.HasKey("Id")
                        .HasName("cash_records_pkey");

                    b.HasIndex(new[] { "PaymentDate" }, "idx_cash_records_date")
                        .IsDescending();

                    b.HasIndex(new[] { "OperationId" }, "idx_cash_records_operation");

                    b.HasIndex(new[] { "FinancialAdjustmentId" }, "uq_cash_records_adjustment")
                        .IsUnique()
                        .HasFilter("(financial_adjustment_id IS NOT NULL)");

                    b.ToTable("cash_records", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_cash_amount", "amount > 0");

                            t.HasCheckConstraint("chk_cash_payment_type", "payment_type in ('CashReceived','CashRefund')");

                            t.HasCheckConstraint("chk_cash_status", "status in ('PendingAccountant','Completed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.FinancialAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("adjustment_type");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("LineageKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lineage_kind")
                        .HasDefaultValueSql("'SourceLinked'::character varying");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("PaymentLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_log_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("ReversesAdjustmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_adjustment_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PendingApproval'::character varying");

                    b.HasKey("Id")
                        .HasName("financial_adjustments_pkey");

                    b.HasIndex(new[] { "MerchantId" }, "idx_financial_adjustments_merchant");

                    b.HasIndex(new[] { "OperationId" }, "idx_financial_adjustments_operation")
                        .HasFilter("(operation_id IS NOT NULL)");

                    b.ToTable("financial_adjustments", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_financial_adjustment_amount", "amount > 0");

                            t.HasCheckConstraint("chk_financial_adjustment_status", "status in ('PendingApproval','Approved','Rejected','Completed','Cancelled','LegacyUnlinked')");

                            t.HasCheckConstraint("chk_financial_adjustment_type", "adjustment_type in ('MerchantCredit','BalanceReduction','CashRefund')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.InstallmentSubLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateOnly>("DateReceived")
                        .HasColumnType("date")
                        .HasColumnName("date_received");

                    b.Property<DateTime>("DraftedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("drafted_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DraftedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("drafted_by");

                    b.Property<Guid>("MainLogId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_log_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("SubLogStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sub_log_status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.HasKey("Id")
                        .HasName("installment_sub_logs_pkey");

                    b.HasIndex(new[] { "MainLogId" }, "idx_sub_logs_main_log");

                    b.HasIndex(new[] { "SubLogStatus" }, "idx_sub_logs_status");

                    b.ToTable("installment_sub_logs", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_sub_log_amount", "amount >= 0");

                            t.HasCheckConstraint("chk_sub_log_payment_method", "payment_method is null or payment_method in ('CashTransaction','CashHandToHand','BankTransfer','Wallet','Installment')");

                            t.HasCheckConstraint("chk_sub_log_status", "sub_log_status in ('Draft','PendingAdminReview','Confirmed','Rejected')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MainPaymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_paid");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("InitializedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("initialized_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("InitializedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initialized_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method")
                        .HasDefaultValueSql("'Installment'::character varying");

                    b.Property<decimal>("PendingAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pending_amount");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PendingAdmin'::character varying");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id")
                        .HasName("main_payment_logs_pkey");

                    b.HasIndex(new[] { "AssignedTo" }, "idx_main_payment_assigned")
                        .HasFilter("(assigned_to IS NOT NULL)");

                    b.HasIndex(new[] { "MerchantId" }, "idx_main_payment_merchant");

                    b.HasIndex(new[] { "OperationId" }, "idx_main_payment_operation");

                    b.HasIndex(new[] { "Status" }, "idx_main_payment_status")
                        .HasFilter("(is_deleted = false)");

                    b.HasIndex(new[] { "OperationId" }, "uq_main_payment_operation_active")
                        .IsUnique()
                        .HasFilter("(is_deleted = false)");

                    b.ToTable("main_payment_logs", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_main_payment_amount_paid", "amount_paid >= 0");

                            t.HasCheckConstraint("chk_main_payment_method", "payment_method in ('CashHandToHand','CashTransaction','Installment')");

                            t.HasCheckConstraint("chk_main_payment_paid_lte_total", "amount_paid + pending_amount <= total_amount");

                            t.HasCheckConstraint("chk_main_payment_pending_amount", "pending_amount >= 0");

                            t.HasCheckConstraint("chk_main_payment_status", "status in ('PendingAdmin','PendingAccountant','PendingAdminReview','Completed','Rejected','Cancelled')");

                            t.HasCheckConstraint("chk_main_payment_total_amount", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.PaymentIdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("key");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("payment_idempotency_keys_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_payment_idempotency_expires_at");

                    b.HasIndex(new[] { "Key", "Scope" }, "uq_payment_idempotency_key_scope")
                        .IsUnique();

                    b.ToTable("payment_idempotency_keys", "payments", t =>
                        {
                            t.HasCheckConstraint("chk_payment_idempotency_status", "status in ('Pending','Completed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.InstallmentSubLog", b =>
                {
                    b.HasOne("Lensee.Modules.Payments.Data.MainPaymentLog", "MainLog")
                        .WithMany("InstallmentSubLogs")
                        .HasForeignKey("MainLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("installment_sub_logs_main_log_id_fkey");

                    b.Navigation("MainLog");
                });

            modelBuilder.Entity("Lensee.Modules.Payments.Data.MainPaymentLog", b =>
                {
                    b.Navigation("InstallmentSubLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
