// <auto-generated />
using System;
using Lensee.Modules.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Identity.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260729154018_AddSystemAuditActor")]
    partial class AddSystemAuditActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lensee.Modules.Identity.Data.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_type");

                    b.Property<string>("ChangedFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("changed_fields");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int?>("StockDeltaApplied")
                        .HasColumnType("integer")
                        .HasColumnName("stock_delta_applied");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("audit_logs_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_audit_logs_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "idx_audit_logs_entity");

                    b.HasIndex(new[] { "UserId" }, "idx_audit_logs_user");

                    b.ToTable("audit_logs", "identity");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("ReplacedBy");

                    b.HasIndex(new[] { "TokenHash" }, "idx_refresh_tokens_hash");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens", "identity");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.RolesPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("roles_permissions_pkey");

                    b.HasIndex(new[] { "Role", "Permission" }, "uq_role_permission")
                        .IsUnique();

                    b.ToTable("roles_permissions", "identity");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "LocationId" }, "idx_users_location");

                    b.HasIndex(new[] { "Role" }, "idx_users_role");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.AuditLog", b =>
                {
                    b.HasOne("Lensee.Modules.Identity.Data.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.RefreshToken", b =>
                {
                    b.HasOne("Lensee.Modules.Identity.Data.RefreshToken", "ReplacedByNavigation")
                        .WithMany("InverseReplacedByNavigation")
                        .HasForeignKey("ReplacedBy")
                        .HasConstraintName("refresh_tokens_replaced_by_fkey");

                    b.HasOne("Lensee.Modules.Identity.Data.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("ReplacedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.RefreshToken", b =>
                {
                    b.Navigation("InverseReplacedByNavigation");
                });

            modelBuilder.Entity("Lensee.Modules.Identity.Data.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
