// <auto-generated />
using System;
using Lensee.Modules.Operations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Operations.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260704161539_AddProductionConstraintsOperations")]
    partial class AddProductionConstraintsOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("operation_number_seq", "operations")
                .StartsAt(1000L);

            modelBuilder.Entity("Lensee.Modules.Operations.Data.InventoryReceiptHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("receipt_date");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("inventory_receipt_headers_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_receipt_headers_operation");

                    b.HasIndex(new[] { "OperationId" }, "inventory_receipt_headers_operation_id_key")
                        .IsUnique();

                    b.ToTable("inventory_receipt_headers", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("BonusQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bonus_quantity");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_mode")
                        .HasDefaultValueSql("'Pieces'::character varying");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LineNotes")
                        .HasColumnType("text")
                        .HasColumnName("line_notes");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_total");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<string>("MerchantNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("merchant_name_snapshot");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RepresentativeNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("representative_name_snapshot");

                    b.Property<string>("Section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("section")
                        .HasDefaultValueSql("'Standard'::character varying");

                    b.Property<string>("SkuCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code_snapshot");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("WriteOffReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("write_off_reason");

                    b.Property<string>("WriteOffReasonText")
                        .HasColumnType("text")
                        .HasColumnName("write_off_reason_text");

                    b.HasKey("Id")
                        .HasName("operation_lines_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_op_lines_operation");

                    b.HasIndex(new[] { "SkuId" }, "idx_op_lines_sku");

                    b.ToTable("operation_lines", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_operation_lines_bonus_quantity", "bonus_quantity >= 0");

                            t.HasCheckConstraint("chk_operation_lines_entry_mode", "entry_mode in ('Packs','Pieces')");

                            t.HasCheckConstraint("chk_operation_lines_line_total", "line_total >= 0");

                            t.HasCheckConstraint("chk_operation_lines_quantity", "quantity >= 0");

                            t.HasCheckConstraint("chk_operation_lines_section", "section in ('Standard','ChangeOut','ChangeIn')");

                            t.HasCheckConstraint("chk_operation_lines_unit_cost", "unit_cost is null or unit_cost >= 0");

                            t.HasCheckConstraint("chk_operation_lines_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_name");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_number")
                        .HasDefaultValueSql("('OP-'::text || to_char(nextval('operations.operation_number_seq'::regclass), 'FM000000'::text))");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_type");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("RepresentativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.HasKey("Id")
                        .HasName("operation_logs_pkey");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex(new[] { "ClientId" }, "idx_op_logs_client")
                        .HasFilter("(client_id IS NOT NULL)");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_op_logs_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "CreatedBy" }, "idx_op_logs_created_by");

                    b.HasIndex(new[] { "SourceLocationId" }, "idx_op_logs_source_location");

                    b.HasIndex(new[] { "OperationType", "Status" }, "idx_op_logs_type_status");

                    b.HasIndex(new[] { "OperationNumber" }, "operation_logs_operation_number_key")
                        .IsUnique();

                    b.ToTable("operation_logs", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_op_payment_method", "payment_method is null or payment_method in ('CashHandToHand','CashTransaction','Installment')");

                            t.HasCheckConstraint("chk_op_status", "status in ('Draft','Confirmed','Completed','Reserved','Shipped','Received','Cancelled')");

                            t.HasCheckConstraint("chk_op_type", "operation_type in ('InventoryReceipt','WarehouseTransfer','WholesaleSale','RetailSale','Reserve','WriteOff','StocktakeAdjustment','Change','Return')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("EditedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("reason")
                        .HasDefaultValueSql("'Initial'::text");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("operation_versions_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_op_versions_operation");

                    b.HasIndex(new[] { "OperationId", "VersionNumber" }, "uq_op_version")
                        .IsUnique();

                    b.ToTable("operation_versions", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeAdjustmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LineNote")
                        .HasColumnType("text")
                        .HasColumnName("line_note");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<int>("PhysicalCount")
                        .HasColumnType("integer")
                        .HasColumnName("physical_count");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int>("SystemQtyBefore")
                        .HasColumnType("integer")
                        .HasColumnName("system_qty_before");

                    b.HasKey("Id")
                        .HasName("stocktake_adjustment_lines_pkey");

                    b.HasIndex(new[] { "SessionId" }, "idx_stocktake_adj_session");

                    b.HasIndex(new[] { "SessionId", "SkuId", "LotNumber", "ExpiryDate" }, "uq_stocktake_line_batch")
                        .IsUnique();

                    b.ToTable("stocktake_adjustment_lines", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<int?>("ProductsCounted")
                        .HasColumnType("integer")
                        .HasColumnName("products_counted");

                    b.Property<DateTime>("SessionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("session_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.Property<int?>("TotalDiscrepancyUnits")
                        .HasColumnType("integer")
                        .HasColumnName("total_discrepancy_units");

                    b.HasKey("Id")
                        .HasName("stocktake_sessions_pkey");

                    b.HasIndex(new[] { "LocationId" }, "idx_stocktake_location");

                    b.ToTable("stocktake_sessions", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_stocktake_status", "status in ('Draft','Confirmed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.InventoryReceiptHeader", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithOne("InventoryReceiptHeader")
                        .HasForeignKey("Lensee.Modules.Operations.Data.InventoryReceiptHeader", "OperationId")
                        .IsRequired()
                        .HasConstraintName("inventory_receipt_headers_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLine", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithMany("OperationLines")
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("operation_lines_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationVersion", "CurrentVersion")
                        .WithMany("OperationLogs")
                        .HasForeignKey("CurrentVersionId")
                        .HasConstraintName("fk_current_version");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithMany("OperationVersions")
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("operation_versions_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeAdjustmentLine", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.StocktakeSession", "Session")
                        .WithMany("StocktakeAdjustmentLines")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("stocktake_adjustment_lines_session_id_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.Navigation("InventoryReceiptHeader");

                    b.Navigation("OperationLines");

                    b.Navigation("OperationVersions");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.Navigation("OperationLogs");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeSession", b =>
                {
                    b.Navigation("StocktakeAdjustmentLines");
                });
#pragma warning restore 612, 618
        }
    }
}
