// <auto-generated />
using System;
using Lensee.Modules.Operations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lensee.Modules.Operations.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260730160627_DirectShopifySkuMatching")]
    partial class DirectShopifySkuMatching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("operation_number_seq", "operations")
                .StartsAt(1000L);

            modelBuilder.Entity("Lensee.Modules.Operations.Data.InventoryReceiptHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("receipt_date");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supplier_name");

                    b.HasKey("Id")
                        .HasName("inventory_receipt_headers_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_receipt_headers_operation");

                    b.HasIndex(new[] { "OperationId" }, "inventory_receipt_headers_operation_id_key")
                        .IsUnique();

                    b.ToTable("inventory_receipt_headers", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("BonusQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bonus_quantity");

                    b.Property<string>("EntryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entry_mode")
                        .HasDefaultValueSql("'Pieces'::character varying");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LineNotes")
                        .HasColumnType("text")
                        .HasColumnName("line_notes");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_total");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<string>("MerchantNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("merchant_name_snapshot");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RepresentativeNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("representative_name_snapshot");

                    b.Property<string>("Section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("section")
                        .HasDefaultValueSql("'Standard'::character varying");

                    b.Property<string>("ShopifyLineItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopify_line_item_id");

                    b.Property<string>("ShopifyPropertiesSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("shopify_properties_snapshot");

                    b.Property<string>("ShopifySkuSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shopify_sku_snapshot");

                    b.Property<string>("ShopifyTitleSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shopify_title_snapshot");

                    b.Property<string>("ShopifyVariantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopify_variant_id");

                    b.Property<string>("ShopifyVariantTitleSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shopify_variant_title_snapshot");

                    b.Property<string>("SkuCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code_snapshot");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("WriteOffReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("write_off_reason");

                    b.Property<string>("WriteOffReasonText")
                        .HasColumnType("text")
                        .HasColumnName("write_off_reason_text");

                    b.HasKey("Id")
                        .HasName("operation_lines_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_op_lines_operation");

                    b.HasIndex(new[] { "SkuId" }, "idx_op_lines_sku");

                    b.ToTable("operation_lines", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_operation_lines_bonus_quantity", "bonus_quantity >= 0");

                            t.HasCheckConstraint("chk_operation_lines_entry_mode", "entry_mode in ('Packs','Pieces')");

                            t.HasCheckConstraint("chk_operation_lines_line_total", "line_total >= 0");

                            t.HasCheckConstraint("chk_operation_lines_quantity", "quantity >= 0");

                            t.HasCheckConstraint("chk_operation_lines_section", "section in ('Standard','ChangeOut','ChangeIn')");

                            t.HasCheckConstraint("chk_operation_lines_unit_cost", "unit_cost is null or unit_cost >= 0");

                            t.HasCheckConstraint("chk_operation_lines_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("buyer_email");

                    b.Property<string>("BuyerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("buyer_phone");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_name");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<string>("CreatedActorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_actor_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_version_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperationNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_number")
                        .HasDefaultValueSql("('OP-'::text || to_char(nextval('operations.operation_number_seq'::regclass), 'FM000000'::text))");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operation_type");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<Guid?>("RepresentativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("representative_id");

                    b.Property<string>("SalesChannel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Manual")
                        .HasColumnName("sales_channel");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text")
                        .HasColumnName("shipping_address");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.HasKey("Id")
                        .HasName("operation_logs_pkey");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex(new[] { "ClientId" }, "idx_op_logs_client")
                        .HasFilter("(client_id IS NOT NULL)");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_op_logs_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "CreatedBy" }, "idx_op_logs_created_by");

                    b.HasIndex(new[] { "SalesChannel" }, "idx_op_logs_sales_channel");

                    b.HasIndex(new[] { "SourceLocationId" }, "idx_op_logs_source_location");

                    b.HasIndex(new[] { "OperationType", "Status" }, "idx_op_logs_type_status");

                    b.HasIndex(new[] { "OperationNumber" }, "operation_logs_operation_number_key")
                        .IsUnique();

                    b.ToTable("operation_logs", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_op_payment_method", "payment_method is null or payment_method in ('CashHandToHand','CashTransaction','Installment')");

                            t.HasCheckConstraint("chk_op_status", "status in ('Draft','Confirmed','Completed','Reserved','Shipped','Received','Cancelled')");

                            t.HasCheckConstraint("chk_op_type", "operation_type in ('InventoryReceipt','WarehouseTransfer','WholesaleSale','RetailSale','Reserve','WriteOff','StocktakeAdjustment','Change','Return')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("EditedActorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("edited_actor_name");

                    b.Property<DateTime>("EditedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("edited_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("reason")
                        .HasDefaultValueSql("'Initial'::text");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("operation_versions_pkey");

                    b.HasIndex(new[] { "OperationId" }, "idx_op_versions_operation");

                    b.HasIndex(new[] { "OperationId", "VersionNumber" }, "uq_op_version")
                        .IsUnique();

                    b.ToTable("operation_versions", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.ShopifyOrderLink", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("payment_reference");

                    b.Property<string>("ShopifyOrderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopify_order_id");

                    b.Property<string>("ShopifyOrderNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopify_order_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OperationId")
                        .HasName("shopify_order_links_pkey");

                    b.HasIndex(new[] { "ShopifyOrderId" }, "uq_shopify_order_links_order")
                        .IsUnique();

                    b.ToTable("shopify_order_links", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.ShopifyWebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ApiVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("api_version");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_id");

                    b.Property<DateTime?>("LeaseUntil")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProtectedPayload")
                        .HasColumnType("text")
                        .HasColumnName("protected_payload");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ShopDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shop_domain");

                    b.Property<string>("ShopifyOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopify_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic");

                    b.Property<DateTime?>("TriggeredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("triggered_at");

                    b.Property<string>("VerificationMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Hmac")
                        .HasColumnName("verification_mode");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("WebhookId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("webhook_id");

                    b.HasKey("Id")
                        .HasName("shopify_webhook_events_pkey");

                    b.HasIndex(new[] { "ShopifyOrderId" }, "idx_shopify_webhook_events_order");

                    b.HasIndex(new[] { "Status", "NextAttemptAt" }, "idx_shopify_webhook_events_ready");

                    b.HasIndex(new[] { "WebhookId" }, "uq_shopify_webhook_events_webhook")
                        .IsUnique();

                    b.ToTable("shopify_webhook_events", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeAdjustmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("LineNote")
                        .HasColumnType("text")
                        .HasColumnName("line_note");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<int>("PhysicalCount")
                        .HasColumnType("integer")
                        .HasColumnName("physical_count");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<int>("SystemQtyBefore")
                        .HasColumnType("integer")
                        .HasColumnName("system_qty_before");

                    b.HasKey("Id")
                        .HasName("stocktake_adjustment_lines_pkey");

                    b.HasIndex(new[] { "SessionId" }, "idx_stocktake_adj_session");

                    b.HasIndex(new[] { "SessionId", "SkuId", "LotNumber", "ExpiryDate" }, "uq_stocktake_line_batch")
                        .IsUnique();

                    b.ToTable("stocktake_adjustment_lines", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<int?>("ProductsCounted")
                        .HasColumnType("integer")
                        .HasColumnName("products_counted");

                    b.Property<DateTime>("SessionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("session_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.Property<int?>("TotalDiscrepancyUnits")
                        .HasColumnType("integer")
                        .HasColumnName("total_discrepancy_units");

                    b.HasKey("Id")
                        .HasName("stocktake_sessions_pkey");

                    b.HasIndex(new[] { "LocationId" }, "idx_stocktake_location");

                    b.ToTable("stocktake_sessions", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_stocktake_status", "status in ('Draft','Confirmed')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<decimal>("CostSubtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_subtotal");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DestinationLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_location_id");

                    b.Property<Guid?>("InventoryReceiptOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_receipt_operation_id");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("LandedTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("landed_total");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("ProductSubtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("product_subtotal");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("shipment_date");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shipment_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Draft'::character varying");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("supply_shipments_pkey");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_supply_shipments_created_at")
                        .IsDescending();

                    b.HasIndex(new[] { "DestinationLocationId" }, "idx_supply_shipments_destination");

                    b.HasIndex(new[] { "InventoryReceiptOperationId" }, "idx_supply_shipments_operation");

                    b.HasIndex(new[] { "Status" }, "idx_supply_shipments_status");

                    b.HasIndex(new[] { "ShipmentNumber" }, "supply_shipments_shipment_number_key")
                        .IsUnique();

                    b.ToTable("supply_shipments", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_supply_shipments_cost_subtotal", "cost_subtotal >= 0");

                            t.HasCheckConstraint("chk_supply_shipments_landed_total", "landed_total >= 0");

                            t.HasCheckConstraint("chk_supply_shipments_product_subtotal", "product_subtotal >= 0");

                            t.HasCheckConstraint("chk_supply_shipments_status", "status in ('Draft','Received','Cancelled')");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cost_type");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id")
                        .HasName("supply_shipment_costs_pkey");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_supply_costs_shipment");

                    b.ToTable("supply_shipment_costs", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_supply_costs_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("SnapshotData")
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot_data");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("supply_shipment_history_pkey");

                    b.HasIndex(new[] { "ShipmentId", "CreatedAt" }, "idx_supply_history_shipment_created")
                        .IsDescending(false, true);

                    b.ToTable("supply_shipment_history", "operations");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("AllocatedCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("allocated_cost");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<decimal>("LandedUnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("landed_unit_cost");

                    b.Property<decimal>("LineSubtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("line_subtotal");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<string>("SkuCodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku_code_snapshot");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("supply_shipment_lines_pkey");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_supply_lines_shipment");

                    b.HasIndex(new[] { "SkuId" }, "idx_supply_lines_sku");

                    b.ToTable("supply_shipment_lines", "operations", t =>
                        {
                            t.HasCheckConstraint("chk_supply_lines_allocated_cost", "allocated_cost >= 0");

                            t.HasCheckConstraint("chk_supply_lines_landed_unit_cost", "landed_unit_cost >= 0");

                            t.HasCheckConstraint("chk_supply_lines_line_subtotal", "line_subtotal >= 0");

                            t.HasCheckConstraint("chk_supply_lines_quantity", "quantity > 0");

                            t.HasCheckConstraint("chk_supply_lines_unit_price", "unit_price is null or unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.InventoryReceiptHeader", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithOne("InventoryReceiptHeader")
                        .HasForeignKey("Lensee.Modules.Operations.Data.InventoryReceiptHeader", "OperationId")
                        .IsRequired()
                        .HasConstraintName("inventory_receipt_headers_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLine", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithMany("OperationLines")
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("operation_lines_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationVersion", "CurrentVersion")
                        .WithMany("OperationLogs")
                        .HasForeignKey("CurrentVersionId")
                        .HasConstraintName("fk_current_version");

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithMany("OperationVersions")
                        .HasForeignKey("OperationId")
                        .IsRequired()
                        .HasConstraintName("operation_versions_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.ShopifyOrderLink", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "Operation")
                        .WithOne("ShopifyOrderLink")
                        .HasForeignKey("Lensee.Modules.Operations.Data.ShopifyOrderLink", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopify_order_links_operation_id_fkey");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeAdjustmentLine", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.StocktakeSession", "Session")
                        .WithMany("StocktakeAdjustmentLines")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("stocktake_adjustment_lines_session_id_fkey");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipment", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.OperationLog", "InventoryReceiptOperation")
                        .WithMany()
                        .HasForeignKey("InventoryReceiptOperationId")
                        .HasConstraintName("supply_shipments_inventory_receipt_operation_id_fkey");

                    b.Navigation("InventoryReceiptOperation");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentCost", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.SupplyShipment", "Shipment")
                        .WithMany("Costs")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("supply_shipment_costs_shipment_id_fkey");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentHistory", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.SupplyShipment", "Shipment")
                        .WithMany("HistoryLogs")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("supply_shipment_history_shipment_id_fkey");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipmentLine", b =>
                {
                    b.HasOne("Lensee.Modules.Operations.Data.SupplyShipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("supply_shipment_lines_shipment_id_fkey");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationLog", b =>
                {
                    b.Navigation("InventoryReceiptHeader");

                    b.Navigation("OperationLines");

                    b.Navigation("OperationVersions");

                    b.Navigation("ShopifyOrderLink");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.OperationVersion", b =>
                {
                    b.Navigation("OperationLogs");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.StocktakeSession", b =>
                {
                    b.Navigation("StocktakeAdjustmentLines");
                });

            modelBuilder.Entity("Lensee.Modules.Operations.Data.SupplyShipment", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("HistoryLogs");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
